### ISSUE TITLE
The pretrained model in few-shot setting？

### ISSUE THREAD

**Issue by LiDaiY** [zju-vipa/NetGraft#1]
Thank you for your code, it is an impressive work. But I'm confused about the pretrained model, for example, the teacher model is trained on full CIFAR10, while the few-shot dataset is still the CIFAR10. There seems to be an intersection between the two dataset(both cifar10). And this seems to go against the few-shot problem. I mean, in few-shot setting, the teacher model is supposed to be trained on the partial categories of CIFAR10, and the rest categories as few shot dataset to train the student model.

**Comment by sccbhxc** [comment]
Our work is about few-shot knowledge distillation, instead of few-shot classification. Few-shot knowledge distillation is a task, which implements knowledge transfer from trained teacher to student using few samples per class. We compare our work with few-shot classification in related work section.
